# Generated by Django 2.1.7 on 2019-03-26 17:49

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Converted_Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='pdfgenerator/media/pdfs/'), upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='pdfgenerator/media/uploads/'), upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
        ),
        migrations.AddField(
            model_name='queue',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfgenerator.Upload', verbose_name='Source File'),
        ),
        migrations.AddField(
            model_name='converted_pdf',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdfgenerator.Upload', verbose_name='Source File'),
        ),
    ]
