# Generated by Django 2.1.7 on 2019-03-25 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0002_auto_20190325_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='destination',
        ),
    ]
