# Generated by Django 2.1.7 on 2019-03-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0005_auto_20190325_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='upload',
            field=models.FileField(upload_to='pdfgenerator/static/pdfs/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='upload',
            field=models.FileField(upload_to='pdfgenerator/static/uploads/'),
        ),
    ]
