# Generated by Django 2.1.7 on 2019-03-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0006_auto_20190325_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Converted_Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfgenerator/static/pdfs/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Download',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='uploaded_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='upload',
            new_name='file',
        ),
    ]
