# Generated by Django 2.1.7 on 2019-03-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0007_auto_20190325_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converted_pdf',
            name='file',
            field=models.FileField(upload_to='pdfgenerator/media/pdfs/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='pdfgenerator/media/uploads/'),
        ),
    ]
