# Generated by Django 2.1.7 on 2019-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0008_auto_20190325_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converted_pdf',
            name='file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
