# Generated by Django 2.1.7 on 2019-03-25 17:50

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgenerator', '0009_auto_20190325_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converted_pdf',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/pdfs/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/uploads/'), upload_to=''),
        ),
    ]
